### ISSUE TITLE
^0.8 & ^0.7 releases depends on alpha dependencies

### ISSUE THREAD

**Issue by PurpleBooth** [memio/spec-gen#2]
Currently in order to use this package without allowing dev dependencies I need to do this

```json
    "memio/spec-gen": "*",
    "memio/memio": "@alpha",
    "memio/linter": "@alpha",
    "memio/validator": "@alpha",
    "memio/model": "@alpha",
    "memio/pretty-printer": "@alpha",
    "memio/twig-template-engine": "@alpha",
```

(substituting the * for the appropriate version), this is a total pain. Can we have tagged releases of the used repositories?

**Comment by gnugat** [comment]
Hey @PurpleBooth! I'll look into it in the following days

**Comment by gnugat** [comment]
Done :white_check_mark:

**Comment by PurpleBooth** [comment]
Thanks! Love the extension btw!
